[package]
name = "dsrs"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_builder = "0.20.2"
indexmap = "2.10.0"
openai-api-rs = "6.0.6"
openrouter-rs = "0.4.4"
rayon = "1.10.0"
reqwest = "0.12.22"
rstest = "0.25.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
smart-default = "0.7.1"
tokio = "1.46.1"
