[package]
name = "dsrs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "test_lm"
path = "scripts/test_lm.rs"

[dependencies]
indexmap = "2.10.0"
openai-api-rs = "6.0.6"
rayon = "1.10.0"
rstest = "0.25.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = "1.46.1"
