[package]
name = "dsrs"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = "2.10.0"
rayon = "1.10.0"
rstest = "0.25.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
