[package]
name = "dsrs_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn   = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
dspy-rs = { path = "../dspy-rs" }
anyhow = "1.0.99"
