name: Lint and Test

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo test --all-features
  
  miri-test:
    name: MIRI Test
    runs-on: ubuntu-latest
    env:
      MIRIFLAGS: -Zmiri-disable-isolation
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@miri
        with:
          toolchain: nightly-2025-05-16  # https://github.com/rust-lang/miri/issues/4323
      - run: cargo miri setup
      - run: cargo miri test --all-features

  clippy:
    name: Clippy Lint
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - run: cargo fmt --check
      - run: cargo clippy --all-targets --all-features
