name: Lint and Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo test
  
  miri-test:
    name: MIRI Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@miri
        with:
          toolchain: nightly-2025-05-16  # https://github.com/rust-lang/miri/issues/4323
      - run: cargo miri setup
      - run: cargo miri test

  clippy:
    name: Clippy Lint
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/cargo@v1
      - run: cargo fmt --check
      - run: cargo clippy --tests -- -Dclippy::all -Dclippy::pedantic
      - run: cargo clippy --all-features --tests -- -Dclippy::all -Dclippy::pedantic

